export { TestappComponent } from "./testapp/testapp.component";
/*export { FruitproductsComponent } from "./fruitproducts/fruitproducts.component";
export { FruitbannerComponent } from "./fruitbanner/fruitbanner.component";
export { FruitbannerboxComponent } from "./fruitbannerbox/fruitbannerbox.component";
export { FruitcestaComponent } from "./fruitcesta/fruitcesta.component";
export { FruitfooterComponent } from "./fruitfooter/fruitfooter.component";
export { FruittopbarComponent } from "./fruittopbar/fruittopbar.component";
export { FruitcartComponent } from "./fruitcart/fruitcart.component";*/
export { PagoComponent } from "./pago/pago.component";
export { PrincipalComponent, } from "./principal/principal.component";
export { ShadibannerComponent, } from "./shadibanner/shadibanner.component";
export { ShadibestsellerComponent } from "./shadibestseller/shadibestseller.component";
export { ShadidiscountComponent } from "./shadidiscount/shadidiscount.component";
export { ShadifooterComponent } from "./shadifooter/shadifooter.component";
export { ShadimostwantedComponent } from "./shadimostwanted/shadimostwanted.component";
export { ShadisliderComponent } from "./shadislider/shadislider.component";
export { ShaditopComponent } from "./shaditop/shaditop.component";
export { ShadishopComponent } from "./shadishop/shadishop.component";
